// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package ecc_manager_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] q;
  } ecc_manager_reg2hw_correctable_mismatches_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } ecc_manager_hw2reg_correctable_mismatches_reg_t;

  // Register -> HW type
  typedef struct packed {
    ecc_manager_reg2hw_correctable_mismatches_reg_t correctable_mismatches; // [31:0]
  } ecc_manager_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    ecc_manager_hw2reg_correctable_mismatches_reg_t correctable_mismatches; // [32:0]
  } ecc_manager_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] ECC_MANAGER_CORRECTABLE_MISMATCHES_OFFSET = 2'h 0;

  // Register index
  typedef enum int {
    ECC_MANAGER_CORRECTABLE_MISMATCHES
  } ecc_manager_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ECC_MANAGER_PERMIT [1] = '{
    4'b 1111  // index[0] ECC_MANAGER_CORRECTABLE_MISMATCHES
  };

endpackage

