// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package hmr_core_regs_reg_pkg;

    localparam HMR_CORE_REGS_REG_TOP_DATA_WIDTH = 32;
    localparam HMR_CORE_REGS_REG_TOP_MIN_ADDR_WIDTH = 4;
    localparam HMR_CORE_REGS_REG_TOP_SIZE = 'hc;

    typedef struct packed {
        logic [28:0] _reserved_31_3;
        logic triple;
        logic dual;
        logic independent;
    } hmr_core__current_mode__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        hmr_core__current_mode__external__fields__in_t rd_data;
    } hmr_core__current_mode__external__in_t;

    typedef struct {
        logic [31:0] next;
        logic we;
    } hmr_core__mismatches__mismatches__in_t;

    typedef struct {
        hmr_core__mismatches__mismatches__in_t mismatches;
    } hmr_core__mismatches__in_t;

    typedef struct {
        hmr_core__current_mode__external__in_t current_mode;
        hmr_core__mismatches__in_t mismatches;
    } hmr_core__in_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } hmr_core__current_mode__external__out_t;

    typedef struct {
        logic [31:0] value;
    } hmr_core__mismatches__mismatches__out_t;

    typedef struct {
        hmr_core__mismatches__mismatches__out_t mismatches;
    } hmr_core__mismatches__out_t;

    typedef struct {
        logic [31:0] value;
        logic swmod;
    } hmr_core__sp_store__sp_store__out_t;

    typedef struct {
        hmr_core__sp_store__sp_store__out_t sp_store;
    } hmr_core__sp_store__out_t;

    typedef struct {
        hmr_core__current_mode__external__out_t current_mode;
        hmr_core__mismatches__out_t mismatches;
        hmr_core__sp_store__out_t sp_store;
    } hmr_core__out_t;
endpackage
