// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module hmr_tmr_regs_reg_top (
        input wire clk,
        input wire arst_n,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [2:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input hmr_tmr_regs_reg_pkg::hmr_tmr__in_t hwif_in,
        output hmr_tmr_regs_reg_pkg::hmr_tmr__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [2:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[2:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic tmr_enable;
        logic tmr_config;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.tmr_enable = cpuif_req_masked & (cpuif_addr == 3'h0);
        decoded_reg_strb.tmr_config = cpuif_req_masked & (cpuif_addr == 3'h4);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } tmr_enable;
        } tmr_enable;
        struct {
            struct {
                logic next;
                logic load_next;
            } delay_resynch;
            struct {
                logic next;
                logic load_next;
            } setback;
            struct {
                logic next;
                logic load_next;
            } reload_setback;
            struct {
                logic next;
                logic load_next;
            } rapid_recovery;
            struct {
                logic next;
                logic load_next;
            } force_resynch;
        } tmr_config;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } tmr_enable;
        } tmr_enable;
        struct {
            struct {
                logic value;
            } delay_resynch;
            struct {
                logic value;
            } setback;
            struct {
                logic value;
            } reload_setback;
            struct {
                logic value;
            } rapid_recovery;
            struct {
                logic value;
            } force_resynch;
        } tmr_config;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: hmr_tmr.tmr_enable.tmr_enable
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tmr_enable.tmr_enable.value;
        load_next_c = '0;
        if(decoded_reg_strb.tmr_enable && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tmr_enable.tmr_enable.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else if(hwif_in.tmr_enable.tmr_enable.we) begin // HW Write - we
            next_c = hwif_in.tmr_enable.tmr_enable.next;
            load_next_c = '1;
        end
        field_combo.tmr_enable.tmr_enable.next = next_c;
        field_combo.tmr_enable.tmr_enable.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.tmr_enable.tmr_enable.value <= 1'h0;
        end else begin
            if(field_combo.tmr_enable.tmr_enable.load_next) begin
                field_storage.tmr_enable.tmr_enable.value <= field_combo.tmr_enable.tmr_enable.next;
            end
        end
    end
    assign hwif_out.tmr_enable.tmr_enable.value = field_storage.tmr_enable.tmr_enable.value;
    // Field: hmr_tmr.tmr_config.delay_resynch
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tmr_config.delay_resynch.value;
        load_next_c = '0;
        if(decoded_reg_strb.tmr_config && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tmr_config.delay_resynch.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else if(hwif_in.tmr_config.delay_resynch.we) begin // HW Write - we
            next_c = hwif_in.tmr_config.delay_resynch.next;
            load_next_c = '1;
        end
        field_combo.tmr_config.delay_resynch.next = next_c;
        field_combo.tmr_config.delay_resynch.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.tmr_config.delay_resynch.value <= 1'h0;
        end else begin
            if(field_combo.tmr_config.delay_resynch.load_next) begin
                field_storage.tmr_config.delay_resynch.value <= field_combo.tmr_config.delay_resynch.next;
            end
        end
    end
    assign hwif_out.tmr_config.delay_resynch.value = field_storage.tmr_config.delay_resynch.value;
    // Field: hmr_tmr.tmr_config.setback
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tmr_config.setback.value;
        load_next_c = '0;
        if(decoded_reg_strb.tmr_config && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tmr_config.setback.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end else if(hwif_in.tmr_config.setback.we) begin // HW Write - we
            next_c = hwif_in.tmr_config.setback.next;
            load_next_c = '1;
        end
        field_combo.tmr_config.setback.next = next_c;
        field_combo.tmr_config.setback.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.tmr_config.setback.value <= 1'h1;
        end else begin
            if(field_combo.tmr_config.setback.load_next) begin
                field_storage.tmr_config.setback.value <= field_combo.tmr_config.setback.next;
            end
        end
    end
    assign hwif_out.tmr_config.setback.value = field_storage.tmr_config.setback.value;
    // Field: hmr_tmr.tmr_config.reload_setback
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tmr_config.reload_setback.value;
        load_next_c = '0;
        if(decoded_reg_strb.tmr_config && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tmr_config.reload_setback.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end else if(hwif_in.tmr_config.reload_setback.we) begin // HW Write - we
            next_c = hwif_in.tmr_config.reload_setback.next;
            load_next_c = '1;
        end
        field_combo.tmr_config.reload_setback.next = next_c;
        field_combo.tmr_config.reload_setback.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.tmr_config.reload_setback.value <= 1'h1;
        end else begin
            if(field_combo.tmr_config.reload_setback.load_next) begin
                field_storage.tmr_config.reload_setback.value <= field_combo.tmr_config.reload_setback.next;
            end
        end
    end
    assign hwif_out.tmr_config.reload_setback.value = field_storage.tmr_config.reload_setback.value;
    // Field: hmr_tmr.tmr_config.rapid_recovery
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tmr_config.rapid_recovery.value;
        load_next_c = '0;
        if(decoded_reg_strb.tmr_config && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tmr_config.rapid_recovery.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end else if(hwif_in.tmr_config.rapid_recovery.we) begin // HW Write - we
            next_c = hwif_in.tmr_config.rapid_recovery.next;
            load_next_c = '1;
        end
        field_combo.tmr_config.rapid_recovery.next = next_c;
        field_combo.tmr_config.rapid_recovery.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.tmr_config.rapid_recovery.value <= 1'h0;
        end else begin
            if(field_combo.tmr_config.rapid_recovery.load_next) begin
                field_storage.tmr_config.rapid_recovery.value <= field_combo.tmr_config.rapid_recovery.next;
            end
        end
    end
    assign hwif_out.tmr_config.rapid_recovery.value = field_storage.tmr_config.rapid_recovery.value;
    // Field: hmr_tmr.tmr_config.force_resynch
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.tmr_config.force_resynch.value;
        load_next_c = '0;
        if(decoded_reg_strb.tmr_config && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.tmr_config.force_resynch.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end else if(hwif_in.tmr_config.force_resynch.we) begin // HW Write - we
            next_c = hwif_in.tmr_config.force_resynch.next;
            load_next_c = '1;
        end
        field_combo.tmr_config.force_resynch.next = next_c;
        field_combo.tmr_config.force_resynch.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.tmr_config.force_resynch.value <= 1'h0;
        end else begin
            if(field_combo.tmr_config.force_resynch.load_next) begin
                field_storage.tmr_config.force_resynch.value <= field_combo.tmr_config.force_resynch.next;
            end
        end
    end
    assign hwif_out.tmr_config.force_resynch.value = field_storage.tmr_config.force_resynch.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[2];
    assign readback_array[0][0:0] = (decoded_reg_strb.tmr_enable && !decoded_req_is_wr) ? field_storage.tmr_enable.tmr_enable.value : '0;
    assign readback_array[0][31:1] = '0;
    assign readback_array[1][0:0] = (decoded_reg_strb.tmr_config && !decoded_req_is_wr) ? field_storage.tmr_config.delay_resynch.value : '0;
    assign readback_array[1][1:1] = (decoded_reg_strb.tmr_config && !decoded_req_is_wr) ? field_storage.tmr_config.setback.value : '0;
    assign readback_array[1][2:2] = (decoded_reg_strb.tmr_config && !decoded_req_is_wr) ? field_storage.tmr_config.reload_setback.value : '0;
    assign readback_array[1][3:3] = (decoded_reg_strb.tmr_config && !decoded_req_is_wr) ? field_storage.tmr_config.rapid_recovery.value : '0;
    assign readback_array[1][4:4] = (decoded_reg_strb.tmr_config && !decoded_req_is_wr) ? field_storage.tmr_config.force_resynch.value : '0;
    assign readback_array[1][31:5] = '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<2; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
