// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package hmr_tmr_regs_reg_pkg;

    localparam HMR_TMR_REGS_REG_TOP_DATA_WIDTH = 32;
    localparam HMR_TMR_REGS_REG_TOP_MIN_ADDR_WIDTH = 3;
    localparam HMR_TMR_REGS_REG_TOP_SIZE = 'h8;

    typedef struct {
        logic next;
        logic we;
    } hmr_tmr__tmr_enable__tmr_enable__in_t;

    typedef struct {
        hmr_tmr__tmr_enable__tmr_enable__in_t tmr_enable;
    } hmr_tmr__tmr_enable__in_t;

    typedef struct {
        logic next;
        logic we;
    } hmr_tmr__tmr_config__delay_resynch__in_t;

    typedef struct {
        logic next;
        logic we;
    } hmr_tmr__tmr_config__setback__in_t;

    typedef struct {
        logic next;
        logic we;
    } hmr_tmr__tmr_config__reload_setback__in_t;

    typedef struct {
        logic next;
        logic we;
    } hmr_tmr__tmr_config__rapid_recovery__in_t;

    typedef struct {
        logic next;
        logic we;
    } hmr_tmr__tmr_config__force_resynch__in_t;

    typedef struct {
        hmr_tmr__tmr_config__delay_resynch__in_t delay_resynch;
        hmr_tmr__tmr_config__setback__in_t setback;
        hmr_tmr__tmr_config__reload_setback__in_t reload_setback;
        hmr_tmr__tmr_config__rapid_recovery__in_t rapid_recovery;
        hmr_tmr__tmr_config__force_resynch__in_t force_resynch;
    } hmr_tmr__tmr_config__in_t;

    typedef struct {
        hmr_tmr__tmr_enable__in_t tmr_enable;
        hmr_tmr__tmr_config__in_t tmr_config;
    } hmr_tmr__in_t;

    typedef struct {
        logic value;
    } hmr_tmr__tmr_enable__tmr_enable__out_t;

    typedef struct {
        hmr_tmr__tmr_enable__tmr_enable__out_t tmr_enable;
    } hmr_tmr__tmr_enable__out_t;

    typedef struct {
        logic value;
    } hmr_tmr__tmr_config__delay_resynch__out_t;

    typedef struct {
        logic value;
    } hmr_tmr__tmr_config__setback__out_t;

    typedef struct {
        logic value;
    } hmr_tmr__tmr_config__reload_setback__out_t;

    typedef struct {
        logic value;
    } hmr_tmr__tmr_config__rapid_recovery__out_t;

    typedef struct {
        logic value;
    } hmr_tmr__tmr_config__force_resynch__out_t;

    typedef struct {
        hmr_tmr__tmr_config__delay_resynch__out_t delay_resynch;
        hmr_tmr__tmr_config__setback__out_t setback;
        hmr_tmr__tmr_config__reload_setback__out_t reload_setback;
        hmr_tmr__tmr_config__rapid_recovery__out_t rapid_recovery;
        hmr_tmr__tmr_config__force_resynch__out_t force_resynch;
    } hmr_tmr__tmr_config__out_t;

    typedef struct {
        hmr_tmr__tmr_enable__out_t tmr_enable;
        hmr_tmr__tmr_config__out_t tmr_config;
    } hmr_tmr__out_t;
endpackage
