// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package hmr_dmr_regs_reg_pkg;

    localparam HMR_DMR_REGS_REG_TOP_DATA_WIDTH = 32;
    localparam HMR_DMR_REGS_REG_TOP_MIN_ADDR_WIDTH = 4;
    localparam HMR_DMR_REGS_REG_TOP_SIZE = 'hc;

    typedef struct {
        logic next;
        logic we;
    } hmr_dmr__dmr_enable__dmr_enable__in_t;

    typedef struct {
        hmr_dmr__dmr_enable__dmr_enable__in_t dmr_enable;
    } hmr_dmr__dmr_enable__in_t;

    typedef struct {
        logic next;
        logic we;
    } hmr_dmr__dmr_config__rapid_recovery__in_t;

    typedef struct {
        logic next;
        logic we;
    } hmr_dmr__dmr_config__force_recovery__in_t;

    typedef struct {
        hmr_dmr__dmr_config__rapid_recovery__in_t rapid_recovery;
        hmr_dmr__dmr_config__force_recovery__in_t force_recovery;
    } hmr_dmr__dmr_config__in_t;

    typedef struct {
        logic [31:0] next;
    } hmr_dmr__checkpoint_addr__checkpoint_addr__in_t;

    typedef struct {
        hmr_dmr__checkpoint_addr__checkpoint_addr__in_t checkpoint_addr;
    } hmr_dmr__checkpoint_addr__in_t;

    typedef struct {
        hmr_dmr__dmr_enable__in_t dmr_enable;
        hmr_dmr__dmr_config__in_t dmr_config;
        hmr_dmr__checkpoint_addr__in_t checkpoint_addr;
    } hmr_dmr__in_t;

    typedef struct {
        logic value;
    } hmr_dmr__dmr_enable__dmr_enable__out_t;

    typedef struct {
        hmr_dmr__dmr_enable__dmr_enable__out_t dmr_enable;
    } hmr_dmr__dmr_enable__out_t;

    typedef struct {
        logic value;
    } hmr_dmr__dmr_config__rapid_recovery__out_t;

    typedef struct {
        logic value;
    } hmr_dmr__dmr_config__force_recovery__out_t;

    typedef struct {
        hmr_dmr__dmr_config__rapid_recovery__out_t rapid_recovery;
        hmr_dmr__dmr_config__force_recovery__out_t force_recovery;
    } hmr_dmr__dmr_config__out_t;

    typedef struct {
        logic [31:0] value;
    } hmr_dmr__checkpoint_addr__checkpoint_addr__out_t;

    typedef struct {
        hmr_dmr__checkpoint_addr__checkpoint_addr__out_t checkpoint_addr;
    } hmr_dmr__checkpoint_addr__out_t;

    typedef struct {
        hmr_dmr__dmr_enable__out_t dmr_enable;
        hmr_dmr__dmr_config__out_t dmr_config;
        hmr_dmr__checkpoint_addr__out_t checkpoint_addr;
    } hmr_dmr__out_t;
endpackage
