// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package hmr_registers_reg_pkg;

    localparam HMR_REGISTERS_REG_TOP_DATA_WIDTH = 32;
    localparam HMR_REGISTERS_REG_TOP_MIN_ADDR_WIDTH = 5;
    localparam HMR_REGISTERS_REG_TOP_SIZE = 'h18;
    localparam NumCores = 'hc;
    localparam NumDMRGroups = 'h6;
    localparam NumTMRGroups = 'h4;

    typedef struct packed {
        logic [22:0] _reserved_31_9;
        logic rapid_recovery;
        logic [4:0] _reserved_7_3;
        logic triple;
        logic dual;
        logic independent;
    } hmr__avail_config__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        hmr__avail_config__external__fields__in_t rd_data;
    } hmr__avail_config__external__in_t;

    typedef struct packed {
        logic [19:0] _reserved_31_12;
        logic [11:0] cores_en;
    } hmr__cores_en__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        hmr__cores_en__external__fields__in_t rd_data;
    } hmr__cores_en__external__in_t;

    typedef struct packed {
        logic [25:0] _reserved_31_6;
        logic [5:0] dmr_enable;
    } hmr__dmr_enable__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        hmr__dmr_enable__external__fields__in_t rd_data;
        logic wr_ack;
    } hmr__dmr_enable__external__in_t;

    typedef struct packed {
        logic [27:0] _reserved_31_4;
        logic [3:0] tmr_enable;
    } hmr__tmr_enable__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        hmr__tmr_enable__external__fields__in_t rd_data;
        logic wr_ack;
    } hmr__tmr_enable__external__in_t;

    typedef struct packed {
        logic [29:0] _reserved_31_2;
        logic force_recovery;
        logic rapid_recovery;
    } hmr__dmr_config__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        hmr__dmr_config__external__fields__in_t rd_data;
        logic wr_ack;
    } hmr__dmr_config__external__in_t;

    typedef struct packed {
        logic [26:0] _reserved_31_5;
        logic force_resynch;
        logic rapid_recovery;
        logic reload_setback;
        logic setback;
        logic delay_resynch;
    } hmr__tmr_config__external__fields__in_t;

    typedef struct {
        logic rd_ack;
        hmr__tmr_config__external__fields__in_t rd_data;
        logic wr_ack;
    } hmr__tmr_config__external__in_t;

    typedef struct {
        hmr__avail_config__external__in_t avail_config;
        hmr__cores_en__external__in_t cores_en;
        hmr__dmr_enable__external__in_t dmr_enable;
        hmr__tmr_enable__external__in_t tmr_enable;
        hmr__dmr_config__external__in_t dmr_config;
        hmr__tmr_config__external__in_t tmr_config;
    } hmr__in_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } hmr__avail_config__external__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
    } hmr__cores_en__external__out_t;

    typedef struct packed {
        logic [25:0] _reserved_31_6;
        logic [5:0] dmr_enable;
    } hmr__dmr_enable__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        hmr__dmr_enable__external__fields__out_t wr_data;
        hmr__dmr_enable__external__fields__out_t wr_biten;
    } hmr__dmr_enable__external__out_t;

    typedef struct packed {
        logic [27:0] _reserved_31_4;
        logic [3:0] tmr_enable;
    } hmr__tmr_enable__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        hmr__tmr_enable__external__fields__out_t wr_data;
        hmr__tmr_enable__external__fields__out_t wr_biten;
    } hmr__tmr_enable__external__out_t;

    typedef struct packed {
        logic [29:0] _reserved_31_2;
        logic force_recovery;
        logic rapid_recovery;
    } hmr__dmr_config__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        hmr__dmr_config__external__fields__out_t wr_data;
        hmr__dmr_config__external__fields__out_t wr_biten;
    } hmr__dmr_config__external__out_t;

    typedef struct packed {
        logic [26:0] _reserved_31_5;
        logic force_resynch;
        logic rapid_recovery;
        logic reload_setback;
        logic setback;
        logic delay_resynch;
    } hmr__tmr_config__external__fields__out_t;

    typedef struct {
        logic req;
        logic req_is_wr;
        hmr__tmr_config__external__fields__out_t wr_data;
        hmr__tmr_config__external__fields__out_t wr_biten;
    } hmr__tmr_config__external__out_t;

    typedef struct {
        hmr__avail_config__external__out_t avail_config;
        hmr__cores_en__external__out_t cores_en;
        hmr__dmr_enable__external__out_t dmr_enable;
        hmr__tmr_enable__external__out_t tmr_enable;
        hmr__dmr_config__external__out_t dmr_config;
        hmr__tmr_config__external__out_t tmr_config;
    } hmr__out_t;
endpackage
