// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module hmr_core_regs_reg_top (
        input wire clk,
        input wire arst_n,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [3:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input hmr_core_regs_reg_pkg::hmr_core__in_t hwif_in,
        output hmr_core_regs_reg_pkg::hmr_core__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [3:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[3:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;
    logic external_req;
    logic external_pending;
    logic external_wr_ack;
    logic external_rd_ack;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            external_pending <= '0;
        end else begin
            if(external_req & ~external_wr_ack & ~external_rd_ack) external_pending <= '1;
            else if(external_wr_ack | external_rd_ack) external_pending <= '0;
            `ifndef SYNTHESIS
                assert_bad_ext_wr_ack: assert(!external_wr_ack || (external_pending | external_req))
                    else $error("An external wr_ack strobe was asserted when no external request was active");
                assert_bad_ext_rd_ack: assert(!external_rd_ack || (external_pending | external_req))
                    else $error("An external rd_ack strobe was asserted when no external request was active");
            `endif
        end
    end

    // Read & write latencies are balanced. Stalls not required
    // except if external
    assign cpuif_req_stall_rd = external_pending;
    assign cpuif_req_stall_wr = external_pending;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic current_mode;
        logic mismatches;
        logic sp_store;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_strb_is_external;

    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_external;
        is_external = '0;
        decoded_reg_strb.current_mode = cpuif_req_masked & (cpuif_addr == 4'h0);
        is_external |= cpuif_req_masked & (cpuif_addr == 4'h0) & !cpuif_req_is_wr;
        decoded_reg_strb.mismatches = cpuif_req_masked & (cpuif_addr == 4'h4);
        decoded_reg_strb.sp_store = cpuif_req_masked & (cpuif_addr == 4'h8);
        decoded_strb_is_external = is_external;
        external_req = is_external;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } mismatches;
        } mismatches;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } sp_store;
        } sp_store;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [31:0] value;
            } mismatches;
        } mismatches;
        struct {
            struct {
                logic [31:0] value;
            } sp_store;
        } sp_store;
    } field_storage_t;
    field_storage_t field_storage;

    
    assign hwif_out.current_mode.req = !decoded_req_is_wr ? decoded_reg_strb.current_mode : '0;
    assign hwif_out.current_mode.req_is_wr = decoded_req_is_wr;
    // Field: hmr_core.mismatches.mismatches
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.mismatches.mismatches.value;
        load_next_c = '0;
        if(decoded_reg_strb.mismatches && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.mismatches.mismatches.value & ~(decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end else if(hwif_in.mismatches.mismatches.we) begin // HW Write - we
            next_c = hwif_in.mismatches.mismatches.next;
            load_next_c = '1;
        end
        field_combo.mismatches.mismatches.next = next_c;
        field_combo.mismatches.mismatches.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.mismatches.mismatches.value <= 32'h0;
        end else begin
            if(field_combo.mismatches.mismatches.load_next) begin
                field_storage.mismatches.mismatches.value <= field_combo.mismatches.mismatches.next;
            end
        end
    end
    assign hwif_out.mismatches.mismatches.value = field_storage.mismatches.mismatches.value;
    // Field: hmr_core.sp_store.sp_store
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.sp_store.sp_store.value;
        load_next_c = '0;
        if(decoded_reg_strb.sp_store && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.sp_store.sp_store.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.sp_store.sp_store.next = next_c;
        field_combo.sp_store.sp_store.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.sp_store.sp_store.value <= 32'h0;
        end else begin
            if(field_combo.sp_store.sp_store.load_next) begin
                field_storage.sp_store.sp_store.value <= field_combo.sp_store.sp_store.next;
            end
        end
    end
    assign hwif_out.sp_store.sp_store.value = field_storage.sp_store.sp_store.value;
    assign hwif_out.sp_store.sp_store.swmod = decoded_reg_strb.sp_store && decoded_req_is_wr && |(decoded_wr_biten[31:0]);

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    always_comb begin
        automatic logic wr_ack;
        wr_ack = '0;
        
        external_wr_ack = wr_ack;
    end
    assign cpuif_wr_ack = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_strb_is_external);
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------
    logic readback_external_rd_ack_c;
    always_comb begin
        automatic logic rd_ack;
        rd_ack = '0;
        rd_ack |= hwif_in.current_mode.rd_ack;
        readback_external_rd_ack_c = rd_ack;
    end

    logic readback_external_rd_ack;

    assign readback_external_rd_ack = readback_external_rd_ack_c;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[3];
    assign readback_array[0] = hwif_in.current_mode.rd_ack ? hwif_in.current_mode.rd_data : '0;
    assign readback_array[1][31:0] = (decoded_reg_strb.mismatches && !decoded_req_is_wr) ? field_storage.mismatches.mismatches.value : '0;
    assign readback_array[2][31:0] = (decoded_reg_strb.sp_store && !decoded_req_is_wr) ? field_storage.sp_store.sp_store.value : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_strb_is_external;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<3; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign external_rd_ack = readback_external_rd_ack;
    assign cpuif_rd_ack = readback_done | readback_external_rd_ack;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
