// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef HMR_REGISTERS_H
#define HMR_REGISTERS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <assert.h>

// Reg - hmr_all::hmr::avail_config
#define HMR_ALL__HMR__AVAIL_CONFIG__INDEPENDENT_bm 0x1
#define HMR_ALL__HMR__AVAIL_CONFIG__INDEPENDENT_bp 0
#define HMR_ALL__HMR__AVAIL_CONFIG__INDEPENDENT_bw 1
#define HMR_ALL__HMR__AVAIL_CONFIG__INDEPENDENT_reset 0x1
#define HMR_ALL__HMR__AVAIL_CONFIG__DUAL_bm 0x2
#define HMR_ALL__HMR__AVAIL_CONFIG__DUAL_bp 1
#define HMR_ALL__HMR__AVAIL_CONFIG__DUAL_bw 1
#define HMR_ALL__HMR__AVAIL_CONFIG__DUAL_reset 0x1
#define HMR_ALL__HMR__AVAIL_CONFIG__TRIPLE_bm 0x4
#define HMR_ALL__HMR__AVAIL_CONFIG__TRIPLE_bp 2
#define HMR_ALL__HMR__AVAIL_CONFIG__TRIPLE_bw 1
#define HMR_ALL__HMR__AVAIL_CONFIG__TRIPLE_reset 0x1
#define HMR_ALL__HMR__AVAIL_CONFIG__RAPID_RECOVERY_bm 0x100
#define HMR_ALL__HMR__AVAIL_CONFIG__RAPID_RECOVERY_bp 8
#define HMR_ALL__HMR__AVAIL_CONFIG__RAPID_RECOVERY_bw 1
#define HMR_ALL__HMR__AVAIL_CONFIG__RAPID_RECOVERY_reset 0x1

// Reg - hmr_all::hmr::cores_en
#define HMR_ALL__HMR__CORES_EN__CORES_EN_bm 0xfff
#define HMR_ALL__HMR__CORES_EN__CORES_EN_bp 0
#define HMR_ALL__HMR__CORES_EN__CORES_EN_bw 12
#define HMR_ALL__HMR__CORES_EN__CORES_EN_reset 0x0

// Reg - hmr_all::hmr::dmr_enable
#define HMR_ALL__HMR__DMR_ENABLE__DMR_ENABLE_bm 0x3f
#define HMR_ALL__HMR__DMR_ENABLE__DMR_ENABLE_bp 0
#define HMR_ALL__HMR__DMR_ENABLE__DMR_ENABLE_bw 6
#define HMR_ALL__HMR__DMR_ENABLE__DMR_ENABLE_reset 0x0

// Reg - hmr_all::hmr::tmr_enable
#define HMR_ALL__HMR__TMR_ENABLE__TMR_ENABLE_bm 0xf
#define HMR_ALL__HMR__TMR_ENABLE__TMR_ENABLE_bp 0
#define HMR_ALL__HMR__TMR_ENABLE__TMR_ENABLE_bw 4
#define HMR_ALL__HMR__TMR_ENABLE__TMR_ENABLE_reset 0x0

// Reg - hmr_all::hmr::dmr_config
#define HMR_ALL__HMR__DMR_CONFIG__RAPID_RECOVERY_bm 0x1
#define HMR_ALL__HMR__DMR_CONFIG__RAPID_RECOVERY_bp 0
#define HMR_ALL__HMR__DMR_CONFIG__RAPID_RECOVERY_bw 1
#define HMR_ALL__HMR__DMR_CONFIG__RAPID_RECOVERY_reset 0x0
#define HMR_ALL__HMR__DMR_CONFIG__FORCE_RECOVERY_bm 0x2
#define HMR_ALL__HMR__DMR_CONFIG__FORCE_RECOVERY_bp 1
#define HMR_ALL__HMR__DMR_CONFIG__FORCE_RECOVERY_bw 1
#define HMR_ALL__HMR__DMR_CONFIG__FORCE_RECOVERY_reset 0x0

// Reg - hmr_all::hmr::tmr_config
#define HMR_ALL__HMR__TMR_CONFIG__DELAY_RESYNCH_bm 0x1
#define HMR_ALL__HMR__TMR_CONFIG__DELAY_RESYNCH_bp 0
#define HMR_ALL__HMR__TMR_CONFIG__DELAY_RESYNCH_bw 1
#define HMR_ALL__HMR__TMR_CONFIG__DELAY_RESYNCH_reset 0x0
#define HMR_ALL__HMR__TMR_CONFIG__SETBACK_bm 0x2
#define HMR_ALL__HMR__TMR_CONFIG__SETBACK_bp 1
#define HMR_ALL__HMR__TMR_CONFIG__SETBACK_bw 1
#define HMR_ALL__HMR__TMR_CONFIG__SETBACK_reset 0x1
#define HMR_ALL__HMR__TMR_CONFIG__RELOAD_SETBACK_bm 0x4
#define HMR_ALL__HMR__TMR_CONFIG__RELOAD_SETBACK_bp 2
#define HMR_ALL__HMR__TMR_CONFIG__RELOAD_SETBACK_bw 1
#define HMR_ALL__HMR__TMR_CONFIG__RELOAD_SETBACK_reset 0x1
#define HMR_ALL__HMR__TMR_CONFIG__RAPID_RECOVERY_bm 0x8
#define HMR_ALL__HMR__TMR_CONFIG__RAPID_RECOVERY_bp 3
#define HMR_ALL__HMR__TMR_CONFIG__RAPID_RECOVERY_bw 1
#define HMR_ALL__HMR__TMR_CONFIG__RAPID_RECOVERY_reset 0x0
#define HMR_ALL__HMR__TMR_CONFIG__FORCE_RESYNCH_bm 0x10
#define HMR_ALL__HMR__TMR_CONFIG__FORCE_RESYNCH_bp 4
#define HMR_ALL__HMR__TMR_CONFIG__FORCE_RESYNCH_bw 1
#define HMR_ALL__HMR__TMR_CONFIG__FORCE_RESYNCH_reset 0x0

// Addrmap - hmr_all::hmr
typedef struct __attribute__ ((__packed__)) {
    uint32_t avail_config;
    uint32_t cores_en;
    uint32_t dmr_enable;
    uint32_t tmr_enable;
    uint32_t dmr_config;
    uint32_t tmr_config;
} hmr_all__hmr_t;

// Reg - hmr_all::hmr_core::current_mode
#define HMR_ALL__HMR_CORE__CURRENT_MODE__INDEPENDENT_bm 0x1
#define HMR_ALL__HMR_CORE__CURRENT_MODE__INDEPENDENT_bp 0
#define HMR_ALL__HMR_CORE__CURRENT_MODE__INDEPENDENT_bw 1
#define HMR_ALL__HMR_CORE__CURRENT_MODE__INDEPENDENT_reset 0x1
#define HMR_ALL__HMR_CORE__CURRENT_MODE__DUAL_bm 0x2
#define HMR_ALL__HMR_CORE__CURRENT_MODE__DUAL_bp 1
#define HMR_ALL__HMR_CORE__CURRENT_MODE__DUAL_bw 1
#define HMR_ALL__HMR_CORE__CURRENT_MODE__DUAL_reset 0x0
#define HMR_ALL__HMR_CORE__CURRENT_MODE__TRIPLE_bm 0x4
#define HMR_ALL__HMR_CORE__CURRENT_MODE__TRIPLE_bp 2
#define HMR_ALL__HMR_CORE__CURRENT_MODE__TRIPLE_bw 1
#define HMR_ALL__HMR_CORE__CURRENT_MODE__TRIPLE_reset 0x0

// Reg - hmr_all::hmr_core::mismatches
#define HMR_ALL__HMR_CORE__MISMATCHES__MISMATCHES_bm 0xffffffff
#define HMR_ALL__HMR_CORE__MISMATCHES__MISMATCHES_bp 0
#define HMR_ALL__HMR_CORE__MISMATCHES__MISMATCHES_bw 32
#define HMR_ALL__HMR_CORE__MISMATCHES__MISMATCHES_reset 0x0

// Reg - hmr_all::hmr_core::sp_store
#define HMR_ALL__HMR_CORE__SP_STORE__SP_STORE_bm 0xffffffff
#define HMR_ALL__HMR_CORE__SP_STORE__SP_STORE_bp 0
#define HMR_ALL__HMR_CORE__SP_STORE__SP_STORE_bw 32
#define HMR_ALL__HMR_CORE__SP_STORE__SP_STORE_reset 0x0

// Addrmap - hmr_all::hmr_core
typedef struct __attribute__ ((__packed__)) {
    uint32_t current_mode;
    uint32_t mismatches;
    uint32_t sp_store;
    uint8_t RESERVED_c_f[0x4];
} hmr_all__hmr_core__stride10_t;

// Reg - hmr_all::hmr_dmr_ispresent_t::dmr_enable
#define HMR_ALL__HMR_DMR_ISPRESENT_T__DMR_ENABLE__DMR_ENABLE_bm 0x1
#define HMR_ALL__HMR_DMR_ISPRESENT_T__DMR_ENABLE__DMR_ENABLE_bp 0
#define HMR_ALL__HMR_DMR_ISPRESENT_T__DMR_ENABLE__DMR_ENABLE_bw 1
#define HMR_ALL__HMR_DMR_ISPRESENT_T__DMR_ENABLE__DMR_ENABLE_reset 0x0

// Reg - hmr_all::hmr_dmr_ispresent_t::dmr_config
#define HMR_ALL__HMR_DMR_ISPRESENT_T__DMR_CONFIG__RAPID_RECOVERY_bm 0x1
#define HMR_ALL__HMR_DMR_ISPRESENT_T__DMR_CONFIG__RAPID_RECOVERY_bp 0
#define HMR_ALL__HMR_DMR_ISPRESENT_T__DMR_CONFIG__RAPID_RECOVERY_bw 1
#define HMR_ALL__HMR_DMR_ISPRESENT_T__DMR_CONFIG__RAPID_RECOVERY_reset 0x0
#define HMR_ALL__HMR_DMR_ISPRESENT_T__DMR_CONFIG__FORCE_RECOVERY_bm 0x2
#define HMR_ALL__HMR_DMR_ISPRESENT_T__DMR_CONFIG__FORCE_RECOVERY_bp 1
#define HMR_ALL__HMR_DMR_ISPRESENT_T__DMR_CONFIG__FORCE_RECOVERY_bw 1
#define HMR_ALL__HMR_DMR_ISPRESENT_T__DMR_CONFIG__FORCE_RECOVERY_reset 0x0

// Reg - hmr_all::hmr_dmr_ispresent_t::checkpoint_addr
#define HMR_ALL__HMR_DMR_ISPRESENT_T__CHECKPOINT_ADDR__CHECKPOINT_ADDR_bm 0xffffffff
#define HMR_ALL__HMR_DMR_ISPRESENT_T__CHECKPOINT_ADDR__CHECKPOINT_ADDR_bp 0
#define HMR_ALL__HMR_DMR_ISPRESENT_T__CHECKPOINT_ADDR__CHECKPOINT_ADDR_bw 32
#define HMR_ALL__HMR_DMR_ISPRESENT_T__CHECKPOINT_ADDR__CHECKPOINT_ADDR_reset 0x0

// Addrmap - hmr_all::hmr_dmr_ispresent_t
typedef struct __attribute__ ((__packed__)) {
    uint32_t dmr_enable;
    uint32_t dmr_config;
    uint32_t checkpoint_addr;
    uint8_t RESERVED_c_f[0x4];
} hmr_all__hmr_dmr_ispresent_t__stride10_t;

// Reg - hmr_all::hmr_tmr_ispresent_t::tmr_enable
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_ENABLE__TMR_ENABLE_bm 0x1
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_ENABLE__TMR_ENABLE_bp 0
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_ENABLE__TMR_ENABLE_bw 1
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_ENABLE__TMR_ENABLE_reset 0x0

// Reg - hmr_all::hmr_tmr_ispresent_t::tmr_config
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__DELAY_RESYNCH_bm 0x1
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__DELAY_RESYNCH_bp 0
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__DELAY_RESYNCH_bw 1
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__DELAY_RESYNCH_reset 0x0
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__SETBACK_bm 0x2
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__SETBACK_bp 1
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__SETBACK_bw 1
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__SETBACK_reset 0x1
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__RELOAD_SETBACK_bm 0x4
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__RELOAD_SETBACK_bp 2
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__RELOAD_SETBACK_bw 1
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__RELOAD_SETBACK_reset 0x1
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__RAPID_RECOVERY_bm 0x8
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__RAPID_RECOVERY_bp 3
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__RAPID_RECOVERY_bw 1
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__RAPID_RECOVERY_reset 0x0
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__FORCE_RESYNCH_bm 0x10
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__FORCE_RESYNCH_bp 4
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__FORCE_RESYNCH_bw 1
#define HMR_ALL__HMR_TMR_ISPRESENT_T__TMR_CONFIG__FORCE_RESYNCH_reset 0x0

// Addrmap - hmr_all::hmr_tmr_ispresent_t
typedef struct __attribute__ ((__packed__)) {
    uint32_t tmr_enable;
    uint32_t tmr_config;
    uint8_t RESERVED_8_f[0x8];
} hmr_all__hmr_tmr_ispresent_t__stride10_t;

// Addrmap - hmr_all
typedef struct __attribute__ ((__packed__)) {
    hmr_all__hmr_t hmr;
    uint8_t RESERVED_18_ff[0xe8];
    hmr_all__hmr_core__stride10_t hmr_core[12];
    uint8_t RESERVED_1c0_1ff[0x40];
    hmr_all__hmr_dmr_ispresent_t__stride10_t hmr_dmr[6];
    uint8_t RESERVED_260_2ff[0xa0];
    hmr_all__hmr_tmr_ispresent_t__stride10_t hmr_tmr[4];
} hmr_all_t;


static_assert(sizeof(hmr_all_t) == 0x340, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* HMR_REGISTERS_H */
