// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 7 -k 32 -s 1592631616 -c hsiao

module prim_secded_39_32_enc (
  input        [31:0] in,
  output logic [38:0] out
);

  always_comb begin : p_encode
    out[31:0] = in;
    out[32] = ^(in & 32'h2CA53295);
    out[33] = ^(in & 32'h93492CA5);
    out[34] = ^(in & 32'h552A5329);
    out[35] = ^(in & 32'hA8D294AA);
    out[36] = ^(in & 32'h4A2CA54A);
    out[37] = ^(in & 32'h25534952);
    out[38] = ^(in & 32'hD294CA54);
  end

endmodule : prim_secded_39_32_enc
