// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 8 -k 64 -s 1592631616 -c hamming

module prim_secded_hamming_72_64_enc (
  input        [63:0] in,
  output logic [71:0] out
);

  always_comb begin : p_encode
    out[63:0] = in;
    out[64] = ^(in & 64'hAB55555556AAAD5B);
    out[65] = ^(in & 64'hCD9999999B33366D);
    out[66] = ^(in & 64'hF1E1E1E1E3C3C78E);
    out[67] = ^(in & 64'h01FE01FE03FC07F0);
    out[68] = ^(in & 64'h01FFFE0003FFF800);
    out[69] = ^(in & 64'h01FFFFFFFC000000);
    out[70] = ^(in & 64'hFE00000000000000);
    out[71] = ^(in & 64'h972CD2D32DA65CB7);
  end

endmodule : prim_secded_hamming_72_64_enc
