// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 4 -k 4 -s 1592631616 -c hsiao

module prim_secded_8_4_enc (
  input        [3:0] in,
  output logic [7:0] out
);

  always_comb begin : p_encode
    out = 8'(in);
    out[4] = ^(out & 8'h07);
    out[5] = ^(out & 8'h0B);
    out[6] = ^(out & 8'h0D);
    out[7] = ^(out & 8'h0E);
  end

endmodule : prim_secded_8_4_enc
