// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 6 -k 22 -s 1592631616 -c hsiao

module prim_secded_28_22_enc (
  input        [21:0] in,
  output logic [27:0] out
);

  always_comb begin : p_encode
    out[21:0] = in;
    out[22] = ^(in & 22'h3003FF);
    out[23] = ^(in & 22'h20FC0F);
    out[24] = ^(in & 22'h171C71);
    out[25] = ^(in & 22'h3B6592);
    out[26] = ^(in & 22'h3DAAA4);
    out[27] = ^(in & 22'h3ED348);
  end

endmodule : prim_secded_28_22_enc
