// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Decoder generated by
// util/design/secded_gen.py -m 4 -k 4 -s 1592631616 -c hsiao

module prim_secded_8_4_dec (
  input        [7:0] in,
  output logic [3:0] d_o,
  output logic [3:0] syndrome_o,
  output logic [1:0] err_o
);

  logic single_error;

  // Syndrome calculation
  assign syndrome_o[0] = ^(in & 8'h17);
  assign syndrome_o[1] = ^(in & 8'h2B);
  assign syndrome_o[2] = ^(in & 8'h4D);
  assign syndrome_o[3] = ^(in & 8'h8E);

  // Corrected output calculation
  assign d_o[0] = (syndrome_o == 4'h7) ^ in[0];
  assign d_o[1] = (syndrome_o == 4'hb) ^ in[1];
  assign d_o[2] = (syndrome_o == 4'hd) ^ in[2];
  assign d_o[3] = (syndrome_o == 4'he) ^ in[3];

  // err_o calc. bit0: single error, bit1: double error
  assign single_error = ^syndrome_o;
  assign err_o[0] = single_error;
  assign err_o[1] = ~single_error & (|syndrome_o);

endmodule : prim_secded_8_4_dec
