// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 7 -k 57 -s 1592631616 -c hsiao

module prim_secded_64_57_enc (
  input        [56:0] in,
  output logic [63:0] out
);

  always_comb begin : p_encode
    out[56:0] = in;
    out[57] = ^(in & 57'h103FFF800007FFF);
    out[58] = ^(in & 57'h17C1FF801FF801F);
    out[59] = ^(in & 57'h1BDE1F87E0781E1);
    out[60] = ^(in & 57'h1DEEE3B8E388E22);
    out[61] = ^(in & 57'h1EF76CDB2C93244);
    out[62] = ^(in & 57'h1F7BB56D5525488);
    out[63] = ^(in & 57'h1FBDDA769A46910);
  end

endmodule : prim_secded_64_57_enc
