// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 8 -k 120 -s 1592631616 -c hsiao

module prim_secded_128_120_enc (
  input        [119:0] in,
  output logic [127:0] out
);

  always_comb begin : p_encode
    out[119:0] = in;
    out[120] = ^(in & 120'h7F000007FFFFFFFF000000001FFFFF);
    out[121] = ^(in & 120'hBF03FFF8000FFFFF00000FFFE0003F);
    out[122] = ^(in & 120'hDF7C1FF83FF003FF003FF003E007C1);
    out[123] = ^(in & 120'hEFBDE1FBC3F0FC0F0FC0F03C207842);
    out[124] = ^(in & 120'hF7DEEE3DDC771C7171C711C4438884);
    out[125] = ^(in & 120'hFBEF76CEED9B6592B65926488C9108);
    out[126] = ^(in & 120'hFDF7BB5776ADAAA4DAAA4A91152210);
    out[127] = ^(in & 120'hFEFBDDA7BB4ED348ED348D221A4420);
  end

endmodule : prim_secded_128_120_enc
