// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 5 -k 11 -s 1592631616 -c hsiao

module prim_secded_16_11_enc (
  input        [10:0] in,
  output logic [15:0] out
);

  always_comb begin : p_encode
    out = 16'(in);
    out[11] = ^(out & 16'h043F);
    out[12] = ^(out & 16'h05C7);
    out[13] = ^(out & 16'h06D9);
    out[14] = ^(out & 16'h076A);
    out[15] = ^(out & 16'h07B4);
  end

endmodule : prim_secded_16_11_enc
