// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 5 -k 8 -s 1592631616 -c hsiao

module prim_secded_13_8_enc (
  input        [7:0] in,
  output logic [12:0] out
);

  always_comb begin : p_encode
    out = 13'(in);
    out[8] = ^(out & 13'h006B);
    out[9] = ^(out & 13'h00F8);
    out[10] = ^(out & 13'h00D5);
    out[11] = ^(out & 13'h00A7);
    out[12] = ^(out & 13'h001E);
  end

endmodule : prim_secded_13_8_enc
