// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 6 -k 16 -s 1592631616 -c hsiao

module prim_secded_22_16_enc (
  input        [15:0] in,
  output logic [21:0] out
);

  always_comb begin : p_encode
    out[15:0] = in;
    out[16] = ^(in & 16'h7B48);
    out[17] = ^(in & 16'h91AB);
    out[18] = ^(in & 16'h0E3D);
    out[19] = ^(in & 16'h7692);
    out[20] = ^(in & 16'hA547);
    out[21] = ^(in & 16'hC8F4);
  end

endmodule : prim_secded_22_16_enc
