// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 5 -k 8 -s 1592631616 -c hsiao

module prim_secded_13_8_enc (
  input        [7:0] in,
  output logic [12:0] out
);

  always_comb begin : p_encode
    out[7:0] = in;
    out[8] = ^(in & 8'h6B);
    out[9] = ^(in & 8'hF8);
    out[10] = ^(in & 8'hD5);
    out[11] = ^(in & 8'hA7);
    out[12] = ^(in & 8'h1E);
  end

endmodule : prim_secded_13_8_enc
