// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Corrector generated by
// util/design/secded_gen.py -m 4 -k 4 -s 1592631616 -c hsiao

module prim_secded_8_4_cor (
  input        [7:0] d_i,
  output logic [7:0] d_o,
  output logic [3:0] syndrome_o,
  output logic [1:0] err_o
);

  logic single_error;

  // Syndrome calculation
  assign syndrome_o[0] = ^(d_i & 8'h17);
  assign syndrome_o[1] = ^(d_i & 8'h2B);
  assign syndrome_o[2] = ^(d_i & 8'h4D);
  assign syndrome_o[3] = ^(d_i & 8'h8E);

  // Corrected output calculation
  assign d_o[0] = (syndrome_o == 4'h7) ^ d_i[0];
  assign d_o[1] = (syndrome_o == 4'hb) ^ d_i[1];
  assign d_o[2] = (syndrome_o == 4'hd) ^ d_i[2];
  assign d_o[3] = (syndrome_o == 4'he) ^ d_i[3];
  assign d_o[4] = (syndrome_o == 4'h1) ^ d_i[4];
  assign d_o[5] = (syndrome_o == 4'h2) ^ d_i[5];
  assign d_o[6] = (syndrome_o == 4'h4) ^ d_i[6];
  assign d_o[7] = (syndrome_o == 4'h8) ^ d_i[7];

  // err_o calc. bit0: single error, bit1: double error
  assign single_error = ^syndrome_o;
  assign err_o[0] = single_error;
  assign err_o[1] = ~single_error & (|syndrome_o);

endmodule : prim_secded_8_4_cor
