// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 5 -k 11 -s 1592631616 -c hsiao

module prim_secded_16_11_enc (
  input        [10:0] in,
  output logic [15:0] out
);

  always_comb begin : p_encode
    out[10:0] = in;
    out[11] = ^(in & 11'h43F);
    out[12] = ^(in & 11'h5C7);
    out[13] = ^(in & 11'h6D9);
    out[14] = ^(in & 11'h76A);
    out[15] = ^(in & 11'h7B4);
  end

endmodule : prim_secded_16_11_enc
