// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 7 -k 32 -s 1592631616 -c hsiao

module prim_secded_39_32_enc (
  input        [31:0] in,
  output logic [38:0] out
);

  always_comb begin : p_encode
    out[31:0] = in;
    out[32] = ^(in & 32'h3800CDBC);
    out[33] = ^(in & 32'hC439C325);
    out[34] = ^(in & 32'h52D82C63);
    out[35] = ^(in & 32'hA4363856);
    out[36] = ^(in & 32'h9B833109);
    out[37] = ^(in & 32'h2DCF42C0);
    out[38] = ^(in & 32'h4364969A);
  end

endmodule : prim_secded_39_32_enc
