// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Corrector generated by
// util/design/secded_gen.py -m 6 -k 16 -s 1592631616 -c hamming

module prim_secded_hamming_22_16_cor (
  input        [21:0] d_i,
  output logic [21:0] d_o,
  output logic [5:0] syndrome_o,
  output logic [1:0] err_o
);


  // Syndrome calculation
  assign syndrome_o[0] = ^(d_i & 22'h01AD5B);
  assign syndrome_o[1] = ^(d_i & 22'h02366D);
  assign syndrome_o[2] = ^(d_i & 22'h04C78E);
  assign syndrome_o[3] = ^(d_i & 22'h0807F0);
  assign syndrome_o[4] = ^(d_i & 22'h10F800);
  assign syndrome_o[5] = ^(d_i & 22'h3FFFFF);

  // Corrected output calculation
  assign d_o[0] = (syndrome_o == 6'h23) ^ d_i[0];
  assign d_o[1] = (syndrome_o == 6'h25) ^ d_i[1];
  assign d_o[2] = (syndrome_o == 6'h26) ^ d_i[2];
  assign d_o[3] = (syndrome_o == 6'h27) ^ d_i[3];
  assign d_o[4] = (syndrome_o == 6'h29) ^ d_i[4];
  assign d_o[5] = (syndrome_o == 6'h2a) ^ d_i[5];
  assign d_o[6] = (syndrome_o == 6'h2b) ^ d_i[6];
  assign d_o[7] = (syndrome_o == 6'h2c) ^ d_i[7];
  assign d_o[8] = (syndrome_o == 6'h2d) ^ d_i[8];
  assign d_o[9] = (syndrome_o == 6'h2e) ^ d_i[9];
  assign d_o[10] = (syndrome_o == 6'h2f) ^ d_i[10];
  assign d_o[11] = (syndrome_o == 6'h31) ^ d_i[11];
  assign d_o[12] = (syndrome_o == 6'h32) ^ d_i[12];
  assign d_o[13] = (syndrome_o == 6'h33) ^ d_i[13];
  assign d_o[14] = (syndrome_o == 6'h34) ^ d_i[14];
  assign d_o[15] = (syndrome_o == 6'h35) ^ d_i[15];
  assign d_o[16] = (syndrome_o == 6'h1) ^ d_i[16];
  assign d_o[17] = (syndrome_o == 6'h2) ^ d_i[17];
  assign d_o[18] = (syndrome_o == 6'h4) ^ d_i[18];
  assign d_o[19] = (syndrome_o == 6'h8) ^ d_i[19];
  assign d_o[20] = (syndrome_o == 6'h10) ^ d_i[20];
  assign d_o[21] = (syndrome_o == 6'h20) ^ d_i[21];

  // err_o calc. bit0: single error, bit1: double error
  assign err_o[0] = syndrome_o[5];
  assign err_o[1] = |syndrome_o[4:0] & ~syndrome_o[5];

endmodule : prim_secded_hamming_22_16_cor
