// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 8 -k 120 -s 1592631616 -c hsiao

module prim_secded_128_120_enc (
  input        [119:0] in,
  output logic [127:0] out
);

  always_comb begin : p_encode
    out = 128'(in);
    out[120] = ^(out & 128'h007F000007FFFFFFFF000000001FFFFF);
    out[121] = ^(out & 128'h00BF03FFF8000FFFFF00000FFFE0003F);
    out[122] = ^(out & 128'h00DF7C1FF83FF003FF003FF003E007C1);
    out[123] = ^(out & 128'h00EFBDE1FBC3F0FC0F0FC0F03C207842);
    out[124] = ^(out & 128'h00F7DEEE3DDC771C7171C711C4438884);
    out[125] = ^(out & 128'h00FBEF76CEED9B6592B65926488C9108);
    out[126] = ^(out & 128'h00FDF7BB5776ADAAA4DAAA4A91152210);
    out[127] = ^(out & 128'h00FEFBDDA7BB4ED348ED348D221A4420);
  end

endmodule : prim_secded_128_120_enc
