// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by
// util/design/secded_gen.py -m 3 -k 1 -s 1592631616 -c hsiao

module prim_secded_4_1_enc (
  input        [0:0] in,
  output logic [3:0] out
);

  always_comb begin : p_encode
    out[0:0] = in;
    out[1] = ^(in & 1'h1);
    out[2] = ^(in & 1'h1);
    out[3] = ^(in & 1'h1);
  end

endmodule : prim_secded_4_1_enc
