// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED Encoder generated by secded_gen.py

module prim_secded_13_8_enc (
  input        [7:0] in,
  output logic [12:0] out
);

  assign out[0] = in[0] ;
  assign out[1] = in[1] ;
  assign out[2] = in[2] ;
  assign out[3] = in[3] ;
  assign out[4] = in[4] ;
  assign out[5] = in[5] ;
  assign out[6] = in[6] ;
  assign out[7] = in[7] ;
  assign out[8] = in[0] ^ in[2] ^ in[3] ^ in[5] ^ in[6];
  assign out[9] = in[1] ^ in[3] ^ in[5] ^ in[6] ^ in[7];
  assign out[10] = in[0] ^ in[2] ^ in[4] ^ in[5] ^ in[7];
  assign out[11] = in[1] ^ in[2] ^ in[4] ^ in[6] ^ in[7];
  assign out[12] = in[0] ^ in[1] ^ in[3] ^ in[4];
endmodule

